//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LessonEntity.EntityFramework.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableProduct
    {
        public int Id { get; set; }
        public string Product { get; set; }
        public decimal Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<decimal> PriceWithDiscount { get; set; }
        public Nullable<int> QuantityOfProduct { get; set; }
    }
}
